Feature/7 registration component
RevatureRideShare/ui-core pull request #100
Opened 2019-12-02 14:54 UTC by cmendezlopez25

2019-12-03 15:12 UTC, jurczakn requested changes

2019-12-03 15:12 UTC, jurczakn commented on RideShare/src/app/registration/registration.component.spec.ts
> +  it('should call onBack method', () => {
remove commented out test

2019-12-04 14:16 UTC, Monjoie11 commented on RideShare/src/app/registration/registration.component.spec.ts
> +  it('should call onBack method', () => {
text has been commented out with requested change pushed

2019-12-04 14:18 UTC, Monjoie11 commented on RideShare/src/app/registration/registration.component.spec.ts
> +  it('should call onBack method', () => {
I mean commented test has been deleted

2019-12-13 15:37 UTC, jurczakn approved these changes
perfect

2019-12-13 15:37 UTC, merged